### PR TITLE
Created a Cocoapod

### PR DESCRIPTION
**Pull request by joeblau**
Added a `.podspec` so you can install this via CocoaPods.

### CODE REVIEW

**Comment by maxkonovalov** [comment]
Hey @joeblau, this is great, thanks! 😉

**Comment by joeblau** [comment]
You might need to fill out some of the stuff in the podspec because I don't know your email address (or if you even want to give that out)

**Comment by maxkonovalov** [comment]
Yea, I'm going to do just that) Will update the repo shortly.

**Comment by maxkonovalov** [comment]
@joeblau I pushed the podspec to trunk - MKRingProgressView is now available via cocoapods 🎉

**Comment by joeblau** [comment]
Awesome! thanks.  BTW awesome work on this library.

**Comment by maxkonovalov** [comment]
@joeblau thanks! I hope you enjoy using it 😀

**Pull request merged**
